name: Release

on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Semver increment (patch, minor, major)'
        type: choice
        default: patch
        options: [patch, minor, major]

permissions:
  contents: write
  id-token: write
  actions: read

concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  build-dist:
    uses: oorabona/release-it-preset/.github/workflows/build-dist.yml@main
    with:
      artifact_name: release-dist-${{ github.sha }}
      ref: ${{ github.sha }}

  validate:
    uses: oorabona/release-it-preset/.github/workflows/reusable-verify.yml@main
    with:
      base-ref: origin/main
      head-ref: ${{ github.sha }}
      run-tests: false
      fetch-depth: 0
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    name: Create Release
    needs: [build-dist, validate]
    outputs:
      tag: ${{ steps.capture-tag.outputs.value }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
      - name: Determine pnpm store path
        id: pnpm-store
        run: echo "path=$(pnpm store path)" >> "$GITHUB_OUTPUT"
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-store.outputs.path }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
          registry-url: https://registry.npmjs.org/

      - run: pnpm install --frozen-lockfile

      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-dist.outputs.artifact_name }}
          path: dist

      - name: Verify dist artifact
        run: |
          if [ ! -f "./dist/index.js" ]; then
            echo "Error: dist/index.js not found in artifact."
            exit 1
          fi
          echo "✓ dist artifact is valid."

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update CHANGELOG
        run: pnpm release-it-preset update

      - name: Validate release
        run: pnpm release-it-preset default --dry-run --increment ${{ github.event.inputs.increment }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run release-it
        run: |
          pnpm release-it-preset default --ci \
            --increment ${{ github.event.inputs.increment }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Capture release tag
        id: capture-tag
        run: echo "value=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"

  publish:
    needs: release
    uses: oorabona/release-it-preset/.github/workflows/publish.yml@main
    with:
      tag: ${{ needs.release.outputs.tag }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
